name: "Build GCC 15"

runs:
  using: "composite"

  steps:
    - name: Restore cached build
      uses: actions/cache/restore@v4
      id: gcc-restore
      with:
        path: ${{ github.workspace }}/gcc-15
        key: gcc-15

    - name: Build GCC 15 when cache miss
      if: steps.gcc-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget https://ftp.gnu.org/gnu/gcc/gcc-15.1.0/gcc-15.1.0.tar.xz
        tar -xf gcc-15.1.0.tar.xz
        cd gcc-15.1.0
        mkdir build
        cd build
        sudo apt install libgmp-dev libmpfr-dev libmpc-dev
        ../configure --prefix=${{ github.workspace }}/gcc-15 --disable-multilib --enable-languages=c,c++
        make -j$(nproc)
        make install

    - name: Cache build
      if: steps.gcc-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/gcc-15
        key: gcc-15