name: Generate and Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: 'windows-latest', compiler: 'msvc' }
          - { os: 'windows-latest', compiler: 'clang' }
          - { os: 'macos-15', compiler: 'clang' }
          - { os: 'ubuntu-latest', compiler: 'clang' }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Generate C++ module binding
        run: python3 generate.py

      - name: Install build dependencies (Windows + Clang)
        if: matrix.os == 'windows-latest' && matrix.compiler == 'clang'
        run: C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -S mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-libc++ mingw-w64-clang-x86_64-libwinpthread-git'

      - name: Install build dependencies (macOS)
        if: matrix.os == 'macos-15'
        run: brew install autoconf automake libtool

      - name: Install build dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get -y update # https://github.com/actions/runner-images/issues/12599
          sudo apt-get install -y libc++-dev libc++abi-dev xorg-dev libltdl-dev

      - name: Enable Developer Command Prompt (Windows + MSVC)
        if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Workaround for CMake bug that cannot find __CMAKE::CXX23 target when using homebrew libc++ (macOS)
        if: matrix.os == 'macos-15'
        run: sed -i '' 's|libc++.modules.json|../../c++/libc++.modules.json|g' /opt/homebrew/opt/cmake/share/cmake/Modules/Compiler/Clang-CXX-CXXImportStd.cmake # https://gitlab.kitware.com/cmake/cmake/-/issues/25965#note_1523575

      - name: Configure
        run: |
          mv .github/workflows/scripts/* examples
          cd examples
          cmake --preset=${{ matrix.os }}-${{ matrix.compiler }}

      - name: Build
        run: cmake --build examples/build --target glfw_vulkan --config Release